function apply_twin_trim
%APPLY_TWIN_TRIM Apply selected twin-engine thrust scaling and trim data.
% The source model must already have been backed up before this function runs.

thisDir = fileparts(mfilename('fullpath'));
oldDir = pwd;
cleanupDir = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(thisDir);

mdl = 'beaver_agent_env';
resultFile = fullfile(thisDir, 'twin_trim_evaluation.mat');
parameterFile = fullfile(thisDir, 'twin_trim_parameters.mat');
reportFile = fullfile(thisDir, 'twin_trim_final_report.txt');
selectedScale = 0.75;

data = load(resultFile, 'results');
level = data.results(9);
engineOut = data.results(10);
descent = data.results(11);
assert(level.success, 'Selected twin-engine level-flight trim did not converge.');
assert(engineOut.success, 'Selected engine-out climb trim did not converge.');
assert(descent.success, 'Selected twin-engine descent trim did not converge.');

if bdIsLoaded(mdl), close_system(mdl, 0); end
load_system(mdl);
cleanupModel = onCleanup(@() close_system(mdl, 0)); %#ok<NASGU>

leftTable = [mdl '/Propulsion_Left/ThrustX'];
rightTable = [mdl '/Propulsion_Right/ThrustX'];
tableExpression = sprintf(['[0, %.16g*getCoefficient(aircraft,"CX","Propeller",' ...
    'Component="Propeller").Table.Value(2:end)]'], selectedScale);
set_param(leftTable, 'DataSpecification', 'Table and breakpoints', ...
    'Table', tableExpression);
set_param(rightTable, 'DataSpecification', 'Table and breakpoints', ...
    'Table', tableExpression);

levelState = level.states;
levelInput = level.inputs;
initialState = descent.states;
initialInput = descent.inputs;
eom = [mdl '/6DOF EOM/6DOF (Euler Angles)'];
set_param(eom, ...
    'xme_0', mat2str([initialState.XN initialState.YE initialState.ZD], 15), ...
    'Vm_0', mat2str([initialState.U initialState.V initialState.W], 15), ...
    'eul_0', mat2str([initialState.phi initialState.theta initialState.psi], 15), ...
    'pm_0', mat2str([initialState.p initialState.q initialState.r], 15));

preLoadFcn = sprintf([ ...
    '[aircraft, state] = astDehavillandBeaver();\n' ...
    'thrustX = getCoefficient(aircraft,"CX","Propeller",Component="Propeller");\n' ...
    'AileronCmd = %.15g;\n' ...
    'ElevatorCmd = %.15g;\n' ...
    'RudderCmd = %.15g;\n' ...
    'Throttle_Left = %.15g;\n' ...
    'Throttle_Right = %.15g;'], ...
    initialInput.AileronCmd, initialInput.ElevatorCmd, initialInput.RudderCmd, ...
    initialInput.Throttle_Common, initialInput.Throttle_Common);
set_param(mdl, 'PreLoadFcn', preLoadFcn);

% Make the defaults available for the validation run in the current session.
evalin('base', '[aircraft, state] = astDehavillandBeaver();');
evalin('base', ['thrustX = getCoefficient(aircraft,"CX","Propeller",' ...
    'Component="Propeller");']);
assignin('base', 'AileronCmd', initialInput.AileronCmd);
assignin('base', 'ElevatorCmd', initialInput.ElevatorCmd);
assignin('base', 'RudderCmd', initialInput.RudderCmd);
assignin('base', 'Throttle_Left', initialInput.Throttle_Common);
assignin('base', 'Throttle_Right', initialInput.Throttle_Common);

save_system(mdl);

params = struct;
params.engineScalePerEngine = selectedScale;
params.engineLateralArm_m = struct('left', -3.5, 'right', 3.5);
params.level = struct( ...
    'control', struct('aileron_rad', levelInput.AileronCmd, ...
        'elevator_rad', levelInput.ElevatorCmd, ...
        'rudder_rad', levelInput.RudderCmd, ...
        'throttleLeft', levelInput.Throttle_Common, ...
        'throttleRight', levelInput.Throttle_Common), ...
    'state', levelState);
params.descent = struct( ...
    'targetVerticalSpeed_mps', -3.0, ...
    'control', struct('aileron_rad', initialInput.AileronCmd, ...
        'elevator_rad', initialInput.ElevatorCmd, ...
        'rudder_rad', initialInput.RudderCmd, ...
        'throttleLeft', initialInput.Throttle_Common, ...
        'throttleRight', initialInput.Throttle_Common), ...
    'state', initialState);
params.engineOutClimb15 = struct( ...
    'failedEngine', 'left', ...
    'targetClimbRate_mps', 1.5, ...
    'control', struct('aileron_rad', engineOut.inputs.AileronCmd, ...
        'elevator_rad', engineOut.inputs.ElevatorCmd, ...
        'rudder_rad', engineOut.inputs.RudderCmd, ...
        'throttleLeft', 0, ...
        'throttleRight', engineOut.inputs.Throttle_Common), ...
    'state', engineOut.states);

params.validation.level = validate_case(mdl, levelState, levelInput, ...
    levelInput.Throttle_Common, levelInput.Throttle_Common, 20);
params.validation.descent = validate_case(mdl, initialState, initialInput, ...
    initialInput.Throttle_Common, initialInput.Throttle_Common, 20);
params.validation.engineOutClimb15 = validate_case(mdl, engineOut.states, ...
    engineOut.inputs, 0, engineOut.inputs.Throttle_Common, 10);

save(parameterFile, 'params');
write_report(reportFile, params, tableExpression);

fprintf('MODEL_SAVED=%s\n', fullfile(thisDir, [mdl '.slx']));
fprintf('PARAMETER_FILE=%s\n', parameterFile);
fprintf('REPORT_FILE=%s\n', reportFile);
fprintf('LEVEL_ALTITUDE_CHANGE_M=%.12g\n', ...
    params.validation.level.altitudeChange_m);
fprintf('LEVEL_TAS_CHANGE_MPS=%.12g\n', ...
    params.validation.level.tasChange_mps);
fprintf('LEVEL_MAX_ABS_ROLL_DEVIATION_RAD=%.12g\n', ...
    params.validation.level.maxAbsRollDeviation_rad);
fprintf('DESCENT_MEAN_VERTICAL_SPEED_MPS=%.12g\n', ...
    params.validation.descent.meanClimbRate_mps);
fprintf('DESCENT_MAX_ABS_ROLL_DEVIATION_RAD=%.12g\n', ...
    params.validation.descent.maxAbsRollDeviation_rad);
fprintf('ENGINE_OUT_MEAN_CLIMB_RATE_MPS=%.12g\n', ...
    params.validation.engineOutClimb15.meanClimbRate_mps);
fprintf('ENGINE_OUT_MAX_ABS_ROLL_DEVIATION_RAD=%.12g\n', ...
    params.validation.engineOutClimb15.maxAbsRollDeviation_rad);
end

function metrics = validate_case(mdl, states, inputs, throttleLeft, throttleRight, stopTime)
eom = [mdl '/6DOF EOM/6DOF (Euler Angles)'];
simIn = Simulink.SimulationInput(mdl);
simIn = simIn.setModelParameter('StartTime', '0', 'StopTime', num2str(stopTime));
simIn = simIn.setVariable('AileronCmd', inputs.AileronCmd);
simIn = simIn.setVariable('ElevatorCmd', inputs.ElevatorCmd);
simIn = simIn.setVariable('RudderCmd', inputs.RudderCmd);
simIn = simIn.setVariable('Throttle_Left', throttleLeft);
simIn = simIn.setVariable('Throttle_Right', throttleRight);
simIn = simIn.setBlockParameter(eom, 'xme_0', ...
    mat2str([states.XN states.YE states.ZD], 15));
simIn = simIn.setBlockParameter(eom, 'Vm_0', ...
    mat2str([states.U states.V states.W], 15));
simIn = simIn.setBlockParameter(eom, 'eul_0', ...
    mat2str([states.phi states.theta states.psi], 15));
simIn = simIn.setBlockParameter(eom, 'pm_0', ...
    mat2str([states.p states.q states.r], 15));
simOut = sim(simIn);

altitude = -double(simOut.Ze.Data(:));
u = double(simOut.u.Data(:));
v = double(simOut.v.Data(:));
w = double(simOut.w.Data(:));
tas = sqrt(u.^2 + v.^2 + w.^2);
phi = double(simOut.phi.Data(:));
p = double(simOut.p.Data(:));
q = double(simOut.q.Data(:));
r = double(simOut.r.Data(:));
time = double(simOut.Ze.Time(:));

metrics = struct;
metrics.duration_s = time(end) - time(1);
metrics.altitudeChange_m = altitude(end) - altitude(1);
metrics.meanClimbRate_mps = metrics.altitudeChange_m / metrics.duration_s;
metrics.tasChange_mps = tas(end) - tas(1);
metrics.maxAbsRollDeviation_rad = max(abs(phi - phi(1)));
metrics.maxAbsBodyRate_radps = [max(abs(p)), max(abs(q)), max(abs(r))];
metrics.finalState = struct('altitude_m', altitude(end), 'tas_mps', tas(end), ...
    'phi_rad', phi(end), 'p_radps', p(end), 'q_radps', q(end), ...
    'r_radps', r(end));
end

function write_report(reportFile, params, tableExpression)
fid = fopen(reportFile, 'w');
assert(fid >= 0, 'Unable to open report file: %s', reportFile);
cleanupFile = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, 'Twin-engine trim configuration and validation\n');
fprintf(fid, 'Generated: %s\n\n', datestr(now, 31));
fprintf(fid, 'Per-engine thrust scale: %.6f\n', params.engineScalePerEngine);
fprintf(fid, 'Lookup table expression: %s\n', tableExpression);
fprintf(fid, 'Engine arms: left y=%.3f m, right y=%.3f m\n\n', ...
    params.engineLateralArm_m.left, params.engineLateralArm_m.right);

lc = params.level.control;
ls = params.level.state;
fprintf(fid, 'Twin-engine level trim at U=45 m/s\n');
fprintf(fid, '  aileron=%.12g rad, elevator=%.12g rad, rudder=%.12g rad\n', ...
    lc.aileron_rad, lc.elevator_rad, lc.rudder_rad);
fprintf(fid, '  throttle left/right=%.12g / %.12g\n', ...
    lc.throttleLeft, lc.throttleRight);
fprintf(fid, '  phi=%.12g rad, theta=%.12g rad, V=%.12g m/s, W=%.12g m/s\n', ...
    ls.phi, ls.theta, ls.V, ls.W);

dc = params.descent.control;
ds = params.descent.state;
fprintf(fid, '\nTwin-engine steady descent, target vertical speed=-3.0 m/s\n');
fprintf(fid, '  aileron=%.12g rad, elevator=%.12g rad, rudder=%.12g rad\n', ...
    dc.aileron_rad, dc.elevator_rad, dc.rudder_rad);
fprintf(fid, '  throttle left/right=%.12g / %.12g\n', ...
    dc.throttleLeft, dc.throttleRight);
fprintf(fid, '  phi=%.12g rad, theta=%.12g rad, V=%.12g m/s, W=%.12g m/s\n', ...
    ds.phi, ds.theta, ds.V, ds.W);

ec = params.engineOutClimb15.control;
es = params.engineOutClimb15.state;
fprintf(fid, '\nLeft-engine-out trim, target climb=1.5 m/s\n');
fprintf(fid, '  aileron=%.12g rad, elevator=%.12g rad, rudder=%.12g rad\n', ...
    ec.aileron_rad, ec.elevator_rad, ec.rudder_rad);
fprintf(fid, '  throttle left/right=%.12g / %.12g\n', ...
    ec.throttleLeft, ec.throttleRight);
fprintf(fid, '  phi=%.12g rad, theta=%.12g rad, V=%.12g m/s, W=%.12g m/s\n', ...
    es.phi, es.theta, es.V, es.W);

lv = params.validation.level;
dv = params.validation.descent;
ev = params.validation.engineOutClimb15;
fprintf(fid, '\nTime-domain validation\n');
fprintf(fid, '  level %g s: dh=%.12g m, dTAS=%.12g m/s, max|dphi|=%.12g rad\n', ...
    lv.duration_s, lv.altitudeChange_m, lv.tasChange_mps, ...
    lv.maxAbsRollDeviation_rad);
fprintf(fid, '  level max|p q r|=%s rad/s\n', ...
    mat2str(lv.maxAbsBodyRate_radps, 12));
fprintf(fid, '  descent %g s: mean vertical speed=%.12g m/s, max|dphi|=%.12g rad\n', ...
    dv.duration_s, dv.meanClimbRate_mps, dv.maxAbsRollDeviation_rad);
fprintf(fid, '  descent max|p q r|=%s rad/s\n', ...
    mat2str(dv.maxAbsBodyRate_radps, 12));
fprintf(fid, '  engine-out %g s: mean climb=%.12g m/s, max|dphi|=%.12g rad\n', ...
    ev.duration_s, ev.meanClimbRate_mps, ev.maxAbsRollDeviation_rad);
fprintf(fid, '  engine-out max|p q r|=%s rad/s\n', ...
    mat2str(ev.maxAbsBodyRate_radps, 12));
end
